trainer:
  max_epochs: 15

other:
  gpus: 2

architecture:
  num_layers: 2
  num_heads: 4
  hidden_features: 32

logging:
  save_dir: ./runs

data:
  data_root: ./data
  num_workers: 4
  batch_size: 128
